/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ideastarter.interfaces;

import com.sun.media.sound.ModelAbstractChannelMixer;
import ideastarter.util.CreateConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thaer
 */
public class GestionProjectUserUpdate extends javax.swing.JFrame {
    Connection conn =null;
    ResultSet rs =null;
    PreparedStatement pst=null;
    DefaultTableModel model;
    /**
     * Creates new form GestionProjectAdminAdd
     */
    
    public GestionProjectUserUpdate() {
        initComponents();
        model=(DefaultTableModel) Tb_Projects.getModel();
        conn=CreateConnection.ConnecrDB();
        UpdateTable();
    }
    
    private void UpdateTable(){
String sql ="select StarName,Combo_StarTag,Description from categorie ";
        try {
            pst =conn.prepareStatement(sql);
            rs=pst.executeQuery();
            Tb_Projects.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            //Logger.getLogger(ImporterImage.class.getName()).log(Level.SEVERE, null, ex);
              JOptionPane.showMessageDialog(null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Tb_Projects1 = new javax.swing.JTable();
        Bt_add_back = new javax.swing.JButton();
        Bt_Add = new javax.swing.JButton();
        StarDescription = new javax.swing.JTextField();
        Lb_add_commentary = new javax.swing.JLabel();
        Lb_Add_title = new javax.swing.JLabel();
        StarName = new javax.swing.JTextField();
        Bt_Delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tb_Projects = new javax.swing.JTable();
        Bt_Update = new javax.swing.JButton();
        Combo_StarTag = new javax.swing.JComboBox();
        label_msg = new javax.swing.JLabel();
        bt_clear = new javax.swing.JButton();
        Lb_add_commentary1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        Tb_Projects1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Star Name", "Star Inventor", "Description"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tb_Projects1.setOpaque(false);
        Tb_Projects1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tb_ProjectsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tb_Projects1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(470, 530));
        getContentPane().setLayout(null);

        Bt_add_back.setText("Back");
        Bt_add_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_add_backActionPerformed(evt);
            }
        });
        getContentPane().add(Bt_add_back);
        Bt_add_back.setBounds(20, 450, 55, 23);

        Bt_Add.setText("add");
        Bt_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_AddActionPerformed(evt);
            }
        });
        getContentPane().add(Bt_Add);
        Bt_Add.setBounds(80, 390, 70, 23);

        StarDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StarDescriptionActionPerformed(evt);
            }
        });
        getContentPane().add(StarDescription);
        StarDescription.setBounds(200, 130, 150, 30);

        Lb_add_commentary.setText("Description");
        getContentPane().add(Lb_add_commentary);
        Lb_add_commentary.setBounds(120, 130, 70, 14);

        Lb_Add_title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Lb_Add_title.setText("Star's Name");
        getContentPane().add(Lb_Add_title);
        Lb_Add_title.setBounds(40, 40, 130, 40);

        StarName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StarNameActionPerformed(evt);
            }
        });
        getContentPane().add(StarName);
        StarName.setBounds(200, 50, 91, 20);

        Bt_Delete.setText("Delete");
        Bt_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Bt_Delete);
        Bt_Delete.setBounds(270, 390, 80, 23);

        Tb_Projects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Star Name", "Tag", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Tb_Projects.setOpaque(false);
        Tb_Projects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tb_ProjectsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tb_Projects);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 190, 350, 180);

        Bt_Update.setText("Modify");
        Bt_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Bt_Update);
        Bt_Update.setBounds(170, 390, 80, 23);

        Combo_StarTag.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Technology", "ART", "Design", "Music", "Food", "Publishing", "Gaming", "Other" }));
        getContentPane().add(Combo_StarTag);
        Combo_StarTag.setBounds(200, 90, 90, 20);
        getContentPane().add(label_msg);
        label_msg.setBounds(210, 440, 70, 0);

        bt_clear.setText("Clear");
        bt_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_clearActionPerformed(evt);
            }
        });
        getContentPane().add(bt_clear);
        bt_clear.setBounds(370, 390, 57, 23);

        Lb_add_commentary1.setText("Tag");
        getContentPane().add(Lb_add_commentary1);
        Lb_add_commentary1.setBounds(150, 90, 30, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ideastarter/Image/managementFond20.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 470, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_add_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_add_backActionPerformed
        // TODO add your handling code here:

        this.dispose();

    }//GEN-LAST:event_Bt_add_backActionPerformed

    private void Bt_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_AddActionPerformed
        // TODO add your handling code here:
//        model.insertRow(model.getRowCount(),new Object[]{StarName.getText(),Combo_StarTag.getSelectedItem(),StarDescription.getText()});
//        JOptionPane.showMessageDialog(null, "file added with success ");
         try {
            String sql ="Insert into categorie (StarName,Combo_StarTag,Description)values(?,?,?)";
             pst=conn.prepareStatement(sql);
             pst.setString(1,StarName.getText());
             pst.setString(2, (String) Combo_StarTag.getSelectedItem());
             pst.setString(3,StarDescription.getText());
             pst.execute();
             JOptionPane.showMessageDialog(null, "saved");
              
        } catch (SQLException ex) {
           // Logger.getLogger(ImporterImage.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
        UpdateTable();
        
    }//GEN-LAST:event_Bt_AddActionPerformed

    private void StarDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StarDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StarDescriptionActionPerformed

    private void StarNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StarNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StarNameActionPerformed

    private void Bt_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_UpdateActionPerformed
        // TODO add your handling code here:
//        model.setValueAt(StarName.getText(), Tb_Projects.getSelectedRow(), 0);
//        model.setValueAt(Combo_StarTag.getSelectedItem(), Tb_Projects.getSelectedRow(), 1);
//        model.setValueAt(StarDescription.getText(), Tb_Projects.getSelectedRow(), 2);
        try {
            String value1 =StarName.getText();
            String value2 =(String) Combo_StarTag.getSelectedItem();
            String value3 =StarDescription.getText();
           
            String sql =" update categorie set StarName='"+value1+"',StarInventor='"+value2+"',Description='"+value3+"' where StarName='"+value1+"' ";
            pst =conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Table Updated");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
         UpdateTable();
        try {
           
        label_msg.setText("");
        
     DefaultTableModel model= (DefaultTableModel)Tb_Projects.getModel();
       if(Tb_Projects.getSelectedRow()==-1){ //si aucune case n'est sélectionée alors si aucun textfild n'est rempli alors "table is empty"
       if (Tb_Projects.getRowCount()==0){label_msg.setText("table is empty"); }
       
       else{label_msg.setText("you must select a TAG ");} // sinn le mesage qu'il dois selectionné quelqu'un sur le tableau 
       }else{
       model.setValueAt(StarName.getText(),Tb_Projects.getSelectedRow(),0);
        model.setValueAt(Combo_StarTag.getActionCommand(),Tb_Projects.getSelectedRow(),1);
       model.setValueAt(StarDescription.getText(),Tb_Projects.getSelectedRow(),2);
       
        }
         } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
       }
        


    }//GEN-LAST:event_Bt_UpdateActionPerformed

    private void Tb_ProjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tb_ProjectsMouseClicked
        // TODO add your handling code here:

//        StarName.setText(String.valueOf(model.getValueAt(Tb_Projects.getSelectedRow(), 0)));
//        //ComboBox1.getSelectedItem(String.valueOf(model.getValueAt(Tb_Projects.getSelectedRow(), 1)));
//        StarDescription.setText(String.valueOf(model.getValueAt(Tb_Projects.getSelectedRow(), 2)));

        int row =Tb_Projects.getSelectedRow();
        String TableClick=Tb_Projects.getModel().getValueAt(row, 0).toString();
       
        
       
        DefaultTableModel model= (DefaultTableModel)Tb_Projects.getModel();
        StarName.setText((String) model.getValueAt(Tb_Projects.getSelectedRow(),0).toString());
        Combo_StarTag.setSelectedItem((String) model.getValueAt(Tb_Projects.getSelectedRow(),1).toString());
        StarDescription.setText((String) model.getValueAt(Tb_Projects.getSelectedRow(),2).toString());
       
                                        
UpdateTable();
    }//GEN-LAST:event_Tb_ProjectsMouseClicked

    private void Bt_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_DeleteActionPerformed
        // TODO add your handling code here:
//        model.removeRow(Tb_Projects.getSelectedRow());
//
//        JOptionPane.showMessageDialog(null, "The project has been deleted with success");
        
         String sql="delete from categorie where StarName= ?";
        try {
            pst =conn.prepareStatement(sql);
            pst.setString(1, StarName.getText());
            
            pst.execute();
            JOptionPane.showMessageDialog(null,"Deleted");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
         DefaultTableModel model= (DefaultTableModel)Tb_Projects.getModel();
         if(Tb_Projects.getSelectedRow()==-1){
        if (Tb_Projects.getRowCount()==0){label_msg.setText("table is empty"); }
        
        else{label_msg.setText("you must select a product");}
        }else{
             model.removeRow(Tb_Projects.getSelectedRow());
         }
         UpdateTable();
    }//GEN-LAST:event_Bt_DeleteActionPerformed

    private void bt_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_clearActionPerformed
        // TODO add your handling code here:
        StarName.setText("");
        Combo_StarTag.setSelectedItem("");
        StarDescription.setText("");
        
    }//GEN-LAST:event_bt_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionProjectUserUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionProjectUserUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionProjectUserUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionProjectUserUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionProjectUserUpdate().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Add;
    private javax.swing.JButton Bt_Delete;
    private javax.swing.JButton Bt_Update;
    private javax.swing.JButton Bt_add_back;
    private javax.swing.JComboBox Combo_StarTag;
    private javax.swing.JLabel Lb_Add_title;
    private javax.swing.JLabel Lb_add_commentary;
    private javax.swing.JLabel Lb_add_commentary1;
    private javax.swing.JTextField StarDescription;
    private javax.swing.JTextField StarName;
    private javax.swing.JTable Tb_Projects;
    private javax.swing.JTable Tb_Projects1;
    private javax.swing.JButton bt_clear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_msg;
    // End of variables declaration//GEN-END:variables
}
