/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ideastarter.interfaces;
import ideastarter.util.CreateConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.lang.*;
import javax.swing.table.DefaultTableModel;
import ideastarter.interfaces.MiseAjourCompteAdmin;

/**
 *
 * @author attia
 */
public class GestionDesComptesAdmins extends javax.swing.JFrame {
    Connection conn =null;
    ResultSet rs =null;
    PreparedStatement pst=null;
    /**
     * Creates new form GestionDesComptesAdmins
     */
    public GestionDesComptesAdmins() {
        initComponents(); 
        conn=CreateConnection.ConnecrDB();
        UpdateTable();
        }
private void UpdateTable(){
String sql ="select Name,LastName,Login,Email from ajoutadmin ";
        try {
            pst =conn.prepareStatement(sql);
            rs=pst.executeQuery();
            table_ajoutadmin.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            //Logger.getLogger(ImporterImage.class.getName()).log(Level.SEVERE, null, ex);
              JOptionPane.showMessageDialog(null, ex);
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_ajoutadmin = new javax.swing.JTable();
        bt_addAccount = new javax.swing.JButton();
        bt_deleteAccount = new javax.swing.JButton();
        bt_updateAccount = new javax.swing.JButton();
        bt_back = new javax.swing.JButton();
        label_msg = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Name = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        table_ajoutadmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nom", "Prenom", "Pseudo", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_ajoutadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_ajoutadminMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_ajoutadmin);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 20, 440, 167);

        bt_addAccount.setText("Add Account");
        bt_addAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addAccountActionPerformed(evt);
            }
        });
        getContentPane().add(bt_addAccount);
        bt_addAccount.setBounds(144, 206, 104, 23);

        bt_deleteAccount.setText("Delete Account");
        bt_deleteAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deleteAccountActionPerformed(evt);
            }
        });
        getContentPane().add(bt_deleteAccount);
        bt_deleteAccount.setBounds(201, 247, 105, 23);

        bt_updateAccount.setText("Update Account");
        bt_updateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_updateAccountActionPerformed(evt);
            }
        });
        getContentPane().add(bt_updateAccount);
        bt_updateAccount.setBounds(266, 206, 109, 23);

        bt_back.setText("Back");
        bt_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_backActionPerformed(evt);
            }
        });
        getContentPane().add(bt_back);
        bt_back.setBounds(40, 290, 55, 23);

        label_msg.setBackground(new java.awt.Color(204, 0, 0));
        label_msg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(label_msg);
        label_msg.setBounds(350, 280, 200, 0);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ideastarter/Image/fond.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -10, 590, 380);
        getContentPane().add(txt_Name);
        txt_Name.setBounds(500, 50, 80, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_addAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addAccountActionPerformed
        new AjoutAdmin().setVisible(true);
        //setVisible(false);
    }//GEN-LAST:event_bt_addAccountActionPerformed

    private void bt_updateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_updateAccountActionPerformed
       
        new MiseAjourCompteAdmin().setVisible(true);
        //setVisible(false);
        
    }//GEN-LAST:event_bt_updateAccountActionPerformed

    private void bt_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_backActionPerformed
        this.dispose();
    }//GEN-LAST:event_bt_backActionPerformed

    private void table_ajoutadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_ajoutadminMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_table_ajoutadminMouseClicked

    private void bt_deleteAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deleteAccountActionPerformed
        // TODO add your handling code here:
         String sql="delete from ajoutadmin where Name = ?";
        try {
            pst =conn.prepareStatement(sql);
            pst.setString(1,txt_Name.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"Deleted");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
         DefaultTableModel model= (DefaultTableModel)table_ajoutadmin.getModel();
        
             model.removeRow(table_ajoutadmin.getSelectedRow());
       
         UpdateTable();
    }//GEN-LAST:event_bt_deleteAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionDesComptesAdmins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionDesComptesAdmins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionDesComptesAdmins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionDesComptesAdmins.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionDesComptesAdmins().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_addAccount;
    private javax.swing.JButton bt_back;
    private javax.swing.JButton bt_deleteAccount;
    private javax.swing.JButton bt_updateAccount;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_msg;
    private javax.swing.JTable table_ajoutadmin;
    private javax.swing.JTextField txt_Name;
    // End of variables declaration//GEN-END:variables

    
}
