/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ideastarter.interfaces;

import ideastarter.util.CreateConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author attia
 */
public class MiseAjourCompteAdmin extends javax.swing.JFrame {

   
Connection conn =null;
    ResultSet rs =null;
    PreparedStatement pst=null;
    /**
     * Creates new form MiseAjourCompteAdmin
     */
    public MiseAjourCompteAdmin() {
        initComponents();
         conn=CreateConnection.ConnecrDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_Name = new javax.swing.JTextField();
        txt_LastName = new javax.swing.JTextField();
        txt_Login = new javax.swing.JTextField();
        Passe_Password = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        bt_updateAccount = new javax.swing.JButton();
        bt_back = new javax.swing.JButton();
        Label_msg = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 450));
        getContentPane().setLayout(null);

        jLabel1.setText("Please Insert the new informations");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(52, 22, 211, 27);

        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 89, 50, 14);

        jLabel3.setText("Last Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 143, 50, 14);

        jLabel4.setText("Login");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 196, 50, 14);

        jLabel6.setText("Password");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 252, 50, 14);

        jLabel7.setText("Email");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 306, 50, 14);

        txt_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Name);
        txt_Name.setBounds(145, 86, 107, 20);
        getContentPane().add(txt_LastName);
        txt_LastName.setBounds(145, 140, 107, 20);
        getContentPane().add(txt_Login);
        txt_Login.setBounds(145, 193, 107, 20);

        Passe_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Passe_PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Passe_Password);
        Passe_Password.setBounds(145, 249, 107, 20);
        getContentPane().add(txt_Email);
        txt_Email.setBounds(145, 300, 107, 20);

        bt_updateAccount.setText("Update Account");
        bt_updateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_updateAccountActionPerformed(evt);
            }
        });
        getContentPane().add(bt_updateAccount);
        bt_updateAccount.setBounds(370, 170, 120, 52);

        bt_back.setText("Back");
        bt_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_backActionPerformed(evt);
            }
        });
        getContentPane().add(bt_back);
        bt_back.setBounds(20, 360, 55, 23);

        Label_msg.setBackground(new java.awt.Color(255, 0, 0));
        Label_msg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(Label_msg);
        Label_msg.setBounds(320, 310, 200, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ideastarter/Image/fond.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, -20, 550, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NameActionPerformed

    private void Passe_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Passe_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Passe_PasswordActionPerformed

    private void bt_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_backActionPerformed
        new GestionDesComptesAdmins().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_bt_backActionPerformed

    private void bt_updateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_updateAccountActionPerformed
        // TODO add your handling code here:
        
         try {
            String value1 =txt_Name.getText();
            String value2 =txt_LastName.getText();
            String value3 =txt_Login.getText();
            String value4 =Passe_Password.getText();
            String value5 =txt_Email.getText();
            String sql =" update ajoutadmin set Name='"+value1+"',LastName='"+value2+"',Login='"+value3+"',Password='"+value4+"',Email='"+value5+"' where Login='"+value3+"' ";
            pst =conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Table Updated");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        new GestionDesComptesAdmins().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_bt_updateAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiseAjourCompteAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiseAjourCompteAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiseAjourCompteAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiseAjourCompteAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiseAjourCompteAdmin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_msg;
    private javax.swing.JTextField Passe_Password;
    private javax.swing.JButton bt_back;
    private javax.swing.JButton bt_updateAccount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_LastName;
    private javax.swing.JTextField txt_Login;
    private javax.swing.JTextField txt_Name;
    // End of variables declaration//GEN-END:variables


    /**
     *
     * @return
     */

}
