/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package StarsUpInterface;

import StarsUpIDAO.IIdeeDAO;
import StarsUpConnexion.DataSource;
import StarsUpDAO.IdeeDAO;
import static StarsUpInterface.GestionProjectUserUpdate.convertUtilDateToSqlDate;
import entities.Idee;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.JFileChooser;
import java.sql.Connection;
import java.sql.Date;
import javax.swing.ImageIcon;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thaer
 */
public final class GestionProjectAdminUpdate extends javax.swing.JFrame {
    
    DefaultTableModel model;
    private IdeeDAO ideeDAO;
    String[] data = new String[]{"id","titre","Category","Description","Start Date","Limit Date","Budget"};
    List<Idee> idees;
    /**
     * Creates new form GestionProjectAdminUpdate
     */
    public GestionProjectAdminUpdate() {
        initComponents();
        
        model = new DefaultTableModel(data, WIDTH);
        TbIdee.setModel(model);
        
        remplirModel();
    }

    public void remplirModel() {
    ideeDAO = new IdeeDAO();
    idees = new ArrayList<>();
    
    idees = ideeDAO.readAll();
    for (Idee idee : idees)
    {
        //System.err.println(idee.getId());
        model.insertRow(model.getRowCount(), new Object[]{idee.getId(),idee.getTitre(),idee.getCategorie(),idee.getDescription(),idee.getDateDebut(),idee.getDateLimite(),idee.getBudgetRequis()});
    }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Bt_add_back = new javax.swing.JButton();
        Bt_Add = new javax.swing.JButton();
        StarDescription = new javax.swing.JTextField();
        Lb_add_commentary = new javax.swing.JLabel();
        Lb_Add_title = new javax.swing.JLabel();
        StarBudget = new javax.swing.JTextField();
        Bt_Delete = new javax.swing.JButton();
        Bt_Update = new javax.swing.JButton();
        label_msg = new javax.swing.JLabel();
        StarTag = new javax.swing.JComboBox();
        Lb_add_commentary2 = new javax.swing.JLabel();
        Lb_add_commentary5 = new javax.swing.JLabel();
        Lb_add_commentary4 = new javax.swing.JLabel();
        Lb_add_commentary6 = new javax.swing.JLabel();
        imp_avatar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbIdee = new javax.swing.JTable();
        StarName1 = new javax.swing.JTextField();
        Lb_add_commentary7 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IdeaStarter/Image/managementFond.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IdeaStarter/Image/managementFond.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 530));
        getContentPane().setLayout(null);

        Bt_add_back.setText("Back");
        Bt_add_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_add_backActionPerformed(evt);
            }
        });
        getContentPane().add(Bt_add_back);
        Bt_add_back.setBounds(20, 450, 55, 23);

        Bt_Add.setText("add");
        Bt_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_AddActionPerformed(evt);
            }
        });
        getContentPane().add(Bt_Add);
        Bt_Add.setBounds(110, 390, 70, 23);

        StarDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StarDescriptionActionPerformed(evt);
            }
        });
        getContentPane().add(StarDescription);
        StarDescription.setBounds(100, 290, 320, 60);

        Lb_add_commentary.setText("Budget Requis");
        getContentPane().add(Lb_add_commentary);
        Lb_add_commentary.setBounds(110, 240, 70, 14);

        Lb_Add_title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Lb_Add_title.setText("Star's Name");
        getContentPane().add(Lb_Add_title);
        Lb_Add_title.setBounds(40, 20, 130, 40);

        StarBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StarBudgetActionPerformed(evt);
            }
        });
        getContentPane().add(StarBudget);
        StarBudget.setBounds(190, 230, 130, 30);

        Bt_Delete.setText("Delete");
        Bt_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Bt_Delete);
        Bt_Delete.setBounds(330, 390, 80, 23);

        Bt_Update.setText("Update");
        Bt_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Bt_Update);
        Bt_Update.setBounds(210, 390, 80, 23);
        getContentPane().add(label_msg);
        label_msg.setBounds(210, 450, 0, 0);

        StarTag.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Technology", "ART", "Design", "Music", "Food", "Publishing", "Gaming", "Other" }));
        StarTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StarTagActionPerformed(evt);
            }
        });
        getContentPane().add(StarTag);
        StarTag.setBounds(190, 80, 90, 20);

        Lb_add_commentary2.setText("Description");
        getContentPane().add(Lb_add_commentary2);
        Lb_add_commentary2.setBounds(30, 290, 60, 14);

        Lb_add_commentary5.setText("Avatar");
        getContentPane().add(Lb_add_commentary5);
        Lb_add_commentary5.setBounds(150, 110, 60, 14);

        Lb_add_commentary4.setText("Tag");
        getContentPane().add(Lb_add_commentary4);
        Lb_add_commentary4.setBounds(150, 80, 30, 14);

        Lb_add_commentary6.setText("Date Limite");
        getContentPane().add(Lb_add_commentary6);
        Lb_add_commentary6.setBounds(120, 200, 60, 14);

        imp_avatar.setText("Import");
        imp_avatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imp_avatarActionPerformed(evt);
            }
        });
        getContentPane().add(imp_avatar);
        imp_avatar.setBounds(190, 110, 65, 23);

        TbIdee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Titre", "Description", "Category", "Start Date", "Limit Date", "Budget"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TbIdee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbIdeeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbIdee);
        TbIdee.getColumnModel().getColumn(0).setHeaderValue("Id");
        TbIdee.getColumnModel().getColumn(1).setHeaderValue("Titre");
        TbIdee.getColumnModel().getColumn(2).setHeaderValue("Description");
        TbIdee.getColumnModel().getColumn(3).setHeaderValue("Category");
        TbIdee.getColumnModel().getColumn(4).setHeaderValue("Start Date");
        TbIdee.getColumnModel().getColumn(5).setHeaderValue("Limit Date");
        TbIdee.getColumnModel().getColumn(6).setHeaderValue("Budget");

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(440, 20, 400, 430);

        StarName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StarName1ActionPerformed(evt);
            }
        });
        getContentPane().add(StarName1);
        StarName1.setBounds(190, 30, 130, 30);

        Lb_add_commentary7.setText("Date Creation");
        getContentPane().add(Lb_add_commentary7);
        Lb_add_commentary7.setBounds(110, 160, 80, 14);

        jDateChooser2.setDateFormatString("dd MMM yyyy");
        getContentPane().add(jDateChooser2);
        jDateChooser2.setBounds(190, 200, 130, 20);

        jDateChooser1.setDateFormatString("dd MMM yyyy");
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(190, 160, 130, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IdeaStarter/Image/fondMan.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 870, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_add_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_add_backActionPerformed
        // TODO add your handling code here:

        this.dispose();

    }//GEN-LAST:event_Bt_add_backActionPerformed

    private void Bt_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_AddActionPerformed
        // TODO add your handling code here:
        java.sql.Date dateDebut;
        java.sql.Date dateLimit;
        Idee idee=new Idee();
        
        idee.setTitre(StarName1.getText());
        idee.setDescription(StarDescription.getText());
        idee.setCategorie(StarTag.getSelectedItem().toString());
        
        dateDebut=convertUtilDateToSqlDate(jDateChooser1.getDate());
        idee.setDateDebut(dateDebut);
        
        dateLimit=convertUtilDateToSqlDate(jDateChooser2.getDate());
        idee.setDateLimite(dateLimit);
        
        idee.setBudgetRequis(Integer.parseInt(StarBudget.getText()));
        
        IdeeDAO ideeDao= new IdeeDAO();
        
        //to update and get the connected client id
        if (ideeDao.createIdee(idee,1)){
          model = new DefaultTableModel(data,WIDTH);
          remplirModel();
         // TbIdee.removeAll();
          TbIdee.setModel(model);
           // model.insertRow(model.getRowCount(), new Object[]{idee.getId(),idee.getTitre(),idee.getDateDebut(),idee.getDateLimite(),idee.getDescription()});
        }
        else {
            JOptionPane.showMessageDialog(null, "echec");
        }
       
    }//GEN-LAST:event_Bt_AddActionPerformed

    private void StarDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StarDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StarDescriptionActionPerformed

    private void StarBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StarBudgetActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_StarBudgetActionPerformed

    private void Bt_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_UpdateActionPerformed
        // TODO add your handling code here:
//        Idee idee=new Idee();
//        idee.setTitre(StarBudget.getText());
//        idee.getCategorie().setTitre(StarTag.getSelectedItem().toString());
//        idee.setDescription(StarDescription.getText());
//        IIdeeDAO ideeDAO= IdeeDAO.getInstance();
//        ideeDAO.updateIdee(idee);
        

    }//GEN-LAST:event_Bt_UpdateActionPerformed

    private void Bt_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_DeleteActionPerformed
        // TODO add your handling code here:
        ideeDAO = new IdeeDAO();
        
        for(int i=0;i<=TbIdee.getSelectedRowCount();i++){
        int id = (int)model.getValueAt(TbIdee.getSelectedRows()[i], 0);
            if(!ideeDAO.deleteIdee(id)){
            JOptionPane.showMessageDialog(null, "echec");
            return;
            }
            model.removeRow(TbIdee.getSelectedRows()[i]);
        }
        JOptionPane.showMessageDialog(null, "Idee supprimé avec succes");
    }//GEN-LAST:event_Bt_DeleteActionPerformed

    private void imp_avatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imp_avatarActionPerformed
        // TODO add your handling code here:
//         JFileChooser chooser=new JFileChooser();
//        chooser.showOpenDialog(null);
//        File f=chooser.getSelectedFile();
//        String filename =f.getAbsolutePath();
//        try {
//            File image =new File(filename);
//            FileInputStream fis =new FileInputStream(image);
//            ByteArrayOutputStream bos = new ByteArrayOutputStream();
//            byte[] buf =new byte[1024];
//            for(int readNum;(readNum=fis.read(buf))!= -1;){
//                bos.write(buf, 0, readNum);
//            }
//             avatar=bos.toByteArray();
//            
//        } catch (Exception e) {
//           JOptionPane.showMessageDialog(null, e);
//        }
       
       
    }//GEN-LAST:event_imp_avatarActionPerformed

    private void StarName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StarName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StarName1ActionPerformed

    private void TbIdeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbIdeeMouseClicked
        // TODO add your handling code here:
        
        StarName1.setText(String.valueOf(model.getValueAt(TbIdee.getSelectedRow(), 1)));
        StarTag.setSelectedItem(String.valueOf(model.getValueAt(TbIdee.getSelectedRow(), 2)));
        StarDescription.setText(String.valueOf(model.getValueAt(TbIdee.getSelectedRow(), 3)));        
        jDateChooser1.setDateFormatString(String.valueOf(model.getValueAt(TbIdee.getSelectedRow(), 4)));
        jDateChooser2.setDateFormatString(String.valueOf(model.getValueAt(TbIdee.getSelectedRow(), 5)));
        StarBudget.setText(String.valueOf(model.getValueAt(TbIdee.getSelectedRow(), 6)));
        
    }//GEN-LAST:event_TbIdeeMouseClicked

    private void StarTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StarTagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StarTagActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionProjectAdminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionProjectAdminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionProjectAdminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionProjectAdminUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GestionProjectAdminUpdate().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Add;
    private javax.swing.JButton Bt_Delete;
    private javax.swing.JButton Bt_Update;
    private javax.swing.JButton Bt_add_back;
    private javax.swing.JLabel Lb_Add_title;
    private javax.swing.JLabel Lb_add_commentary;
    private javax.swing.JLabel Lb_add_commentary2;
    private javax.swing.JLabel Lb_add_commentary4;
    private javax.swing.JLabel Lb_add_commentary5;
    private javax.swing.JLabel Lb_add_commentary6;
    private javax.swing.JLabel Lb_add_commentary7;
    private javax.swing.JTextField StarBudget;
    private javax.swing.JTextField StarDescription;
    private javax.swing.JTextField StarName1;
    private javax.swing.JComboBox StarTag;
    private javax.swing.JTable TbIdee;
    private javax.swing.JButton imp_avatar;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_msg;
    // End of variables declaration//GEN-END:variables

    //byte[] avatar=null;

    
}
