/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package StarsUpInterface;

import StarsUpIDAO.IIdeeDAO;
import StarsUpConnexion.DataSource;
import StarsUpDAO.ContributionDAO;
import StarsUpDAO.IdeeDAO;
import entities.Client;
import entities.Contribution;
import entities.Idee;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thaer
 */
public final class GestionProjectUserContributions extends javax.swing.JFrame {
    
    DefaultTableModel model;
    private IdeeDAO ideeDAO;
    String[] data = new String[]{"Client's Name","Value","Contirbution Date"};
    List<Contribution> contributions;
    /**
     * Creates new form GestionProjectAdminUpdate
     */
    public GestionProjectUserContributions() {
        initComponents();
        
        model = new DefaultTableModel(data, WIDTH);
        TbContribution.setModel(model);
        
        remplirModel();
    }
    
        Client currentClient = new Client();

    public GestionProjectUserContributions(int id,Client currentClient){
        initComponents();
        
        Idee idee = new Idee();
        IdeeDAO idao = new IdeeDAO();
        
        
        idee = idao.getById(id);
        
        Lb_Project_ProjectName.setText(idee.getTitre());
    }
    
     Idee currentIdee = new Idee();

    public void remplirModel() {
    ContributionDAO contributionDAO = new ContributionDAO();
    contributions = new ArrayList<>();
    contributions = contributionDAO.readAll();
    for (Contribution contribution : contributions)
    {
        model.insertRow(model.getRowCount(), new Object[]{contribution.getClient().getNom(),contribution.getValeur(),contribution.getDateContribution()});
    }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        StarName1 = new javax.swing.JTextField();
        Bt_add_back = new javax.swing.JButton();
        Bt_Add = new javax.swing.JButton();
        label_msg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbContribution = new javax.swing.JTable();
        Lb_Project_ProjectName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IdeaStarter/Image/managementFond.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IdeaStarter/Image/managementFond.png"))); // NOI18N

        StarName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StarName1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 530));
        getContentPane().setLayout(null);

        Bt_add_back.setText("Back");
        Bt_add_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_add_backActionPerformed(evt);
            }
        });
        getContentPane().add(Bt_add_back);
        Bt_add_back.setBounds(40, 430, 55, 23);

        Bt_Add.setText("add");
        Bt_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_AddActionPerformed(evt);
            }
        });
        getContentPane().add(Bt_Add);
        Bt_Add.setBounds(210, 370, 80, 23);
        getContentPane().add(label_msg);
        label_msg.setBounds(210, 450, 0, 0);

        TbContribution.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Client's Name", "Value", "Contribution Date"
            }
        ));
        TbContribution.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbContributionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbContribution);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 150, 370, 150);

        Lb_Project_ProjectName.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Lb_Project_ProjectName.setText("Star's Name");
        Lb_Project_ProjectName.setOpaque(true);
        getContentPane().add(Lb_Project_ProjectName);
        Lb_Project_ProjectName.setBounds(110, 60, 270, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IdeaStarter/Image/fondMan.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 480, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_add_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_add_backActionPerformed
        // TODO add your handling code here:

         new ProjectHome().setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_Bt_add_backActionPerformed

    private void Bt_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_AddActionPerformed
        // TODO add your handling code here:

//        Contribution contribution=new Contribution();
//        
//        contribution.setTitre(StarName1.getText());
//        
//        
//        IIdeeDAO ideeDao= new IdeeDAO();
//        
//        //to update and get the connected client id
//        if (ideeDao.createIdee(idee,1)){
//          model = new DefaultTableModel(data,WIDTH);
//          remplirModel();
//         // TbIdee.removeAll();
//          TbContribution.setModel(model);
//           // model.insertRow(model.getRowCount(), new Object[]{idee.getId(),idee.getTitre(),idee.getDateDebut(),idee.getDateLimite(),idee.getDescription()});
//        }
//        else {
//            JOptionPane.showMessageDialog(null, "echec");
//        }
       
    }//GEN-LAST:event_Bt_AddActionPerformed

    private void StarName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StarName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StarName1ActionPerformed

    private void TbContributionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbContributionMouseClicked
        // TODO add your handling code here:
            
    }//GEN-LAST:event_TbContributionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionProjectUserContributions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionProjectUserContributions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionProjectUserContributions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionProjectUserContributions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GestionProjectUserContributions().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_Add;
    private javax.swing.JButton Bt_add_back;
    private javax.swing.JLabel Lb_Project_ProjectName;
    private javax.swing.JTextField StarName1;
    private javax.swing.JTable TbContribution;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_msg;
    // End of variables declaration//GEN-END:variables

  
}
