/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package StarsUpInterface;

import StarsUpConnexion.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import StarsUpDAO.NotificationDao;

/**
 *
 * @author Administrateur
 */
public class GestionNotification extends javax.swing.JFrame {

        private Connection conn ;
    ResultSet rs =null;
    PreparedStatement pst=null;
    
    /**
     * Creates new form Notification
     */
    public GestionNotification() {
        initComponents();
        conn= DataSource.getInstance().getConnection();
        curentDate();
    }
    
    public void curentDate() {
        Thread clock =new Thread(){
    public void run(){
   
        
    GregorianCalendar cal =new GregorianCalendar();
    int month=cal.get(Calendar.MONTH);
    int day=cal.get(Calendar.DAY_OF_MONTH);
    int year=cal.get(Calendar.YEAR);
    txt_date.setText(+day +"/"+(month+1)+"/"+year);
    
    

//        try {
//             String sql ="Insert into DATE (month,year,day)values(?,?,?)";
//             pst=conn.prepareStatement(sql);
//             pst.setInt(1,month);
//             pst.setInt(2, year);
//             pst.setInt(3,day);
//             pst.execute();
//        } catch (SQLException ex) {
//           // Logger.getLogger(date.class.getName()).log(Level.SEVERE, null, ex);
//            JOptionPane.showMessageDialog(null, ex);
//        } 
        


//catch(InterruptedException ex){
//Logger.getLogger(Time.class.getName()).log(Level.SEVERE);
//}
    }
    
  
    
    };
    
    clock.start();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_date = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_text = new javax.swing.JTextArea();
        bt_Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 0, 24)); // NOI18N
        jLabel2.setText("Notification");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 30, 170, 40);

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        getContentPane().add(txt_id);
        txt_id.setBounds(200, 190, 160, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Text");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 270, 80, 30);

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 420, 70, 30);

        txt_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dateActionPerformed(evt);
            }
        });
        getContentPane().add(txt_date);
        txt_date.setBounds(200, 120, 150, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Date");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 120, 60, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("User Id");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 190, 90, 30);

        txt_text.setColumns(20);
        txt_text.setRows(5);
        jScrollPane1.setViewportView(txt_text);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(200, 250, 106, 61);

        bt_Back.setText("Back");
        bt_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_BackActionPerformed(evt);
            }
        });
        getContentPane().add(bt_Back);
        bt_Back.setBounds(300, 420, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IdeaStarter/Image/managementFond.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 530, 530);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GregorianCalendar cal =new GregorianCalendar();
        
         try {
            String sql ="Insert into Notification (administrateur_id,client_id,texte_notification,day,month,year)values(?,?,?,?,?,?)";
             pst=conn.prepareStatement(sql);
             
             pst.setInt(1,5);
             pst.setInt(2,3);
             pst.setString(3,txt_text.getText());
            pst.setInt(4, cal.get(Calendar.DAY_OF_MONTH));
             pst.setInt(5, cal.get(Calendar.MONTH));
             pst.setInt(6,cal.get(Calendar.YEAR));
             pst.execute();
             
          
             pst.execute();
             JOptionPane.showMessageDialog(null, "Notification is sent");
              
        } catch (SQLException ex) {
           // Logger.getLogger(ImporterImage.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
        
        
       GestionHome gh = new GestionHome();
        gh.setVisible(true);
        this.setVisible(false);
    
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_BackActionPerformed
        GestionHome appelFenetre = new GestionHome();
        appelFenetre.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_bt_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionNotification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionNotification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionNotification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionNotification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionNotification().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Back;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextArea txt_text;
    // End of variables declaration//GEN-END:variables
}
